import type { Metadata } from "next";
import { Children } from "react";
import Navbar from "./_components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden">
       <div className="flex flex-col h-full">
        <Navbar />
        <main className="flex-1 overflow-y-auto container mx-auto px-4 py-8">
        {children}</main>
       </div>
      </body>
    </html>
  );
}